### ISSUE TITLE
Consider break down architecture design using Class Diagram (at package level)

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxDownloader#5]
Before we start writing code, we'll imagine what's the code looks like.
Start from a design (at package level) to state its responsibility,  function, dependencies.
It'll also help if we want to use tools like Dagger or design patterns to fit our needs.

[StarUML](http://staruml.io/), or even whiteboarding (remember to take a photo and upload to the issue) may also help:)

**Comment by manddy** [comment]
@cnevinc  working on it
