### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxDownloader#9]
The demo app should be at least demonstrate how the main usage of this library

## Trigger and schedule a download.
. (P1) trigger a download via an intent or API call. 
. (P1) how to schedule and re-schedule the download.
. (P2) how to remove a pending download.
. (P1) Display a setting page to show all the scheduled download
. (P1) Display a notification for each downloading task.
. (P1) Display one notification when there's at least one pending task. When the user clicks on the notification, open the app and display a setting page
. (P1) After triggering the download, the user can set up the date/time to download
. (P1) After launching the app, the user can see a list of downloaded items.
. (P2) If the item is removed, the item will be removed or marked as removed.

## Enhance function
. (P2) Move to SD card
. (P2) Move storage location
. (P2) Integrate with Firefox Lite

**Comment by manddy** [comment]
@cnevinc  Taken a note of it, working on it.
